/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'
import { Route as AuthenticatedPlanesRouteImport } from './routes/_authenticated/planes'
import { Route as AuthenticatedPinesRouteImport } from './routes/_authenticated/pines'
import { Route as AuthenticatedImpresionesRouteImport } from './routes/_authenticated/impresiones'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanesRoute = AuthenticatedPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPinesRoute = AuthenticatedPinesRouteImport.update({
  id: '/pines',
  path: '/pines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpresionesRoute =
  AuthenticatedImpresionesRouteImport.update({
    id: '/impresiones',
    path: '/impresiones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/impresiones': typeof AuthenticatedImpresionesRoute
  '/pines': typeof AuthenticatedPinesRoute
  '/planes': typeof AuthenticatedPlanesRoute
  '/ventas': typeof AuthenticatedVentasRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/impresiones': typeof AuthenticatedImpresionesRoute
  '/pines': typeof AuthenticatedPinesRoute
  '/planes': typeof AuthenticatedPlanesRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/impresiones': typeof AuthenticatedImpresionesRoute
  '/_authenticated/pines': typeof AuthenticatedPinesRoute
  '/_authenticated/planes': typeof AuthenticatedPlanesRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/impresiones' | '/pines' | '/planes' | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/impresiones' | '/pines' | '/planes' | '/ventas' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/impresiones'
    | '/_authenticated/pines'
    | '/_authenticated/planes'
    | '/_authenticated/ventas'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planes': {
      id: '/_authenticated/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof AuthenticatedPlanesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pines': {
      id: '/_authenticated/pines'
      path: '/pines'
      fullPath: '/pines'
      preLoaderRoute: typeof AuthenticatedPinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impresiones': {
      id: '/_authenticated/impresiones'
      path: '/impresiones'
      fullPath: '/impresiones'
      preLoaderRoute: typeof AuthenticatedImpresionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedImpresionesRoute: typeof AuthenticatedImpresionesRoute
  AuthenticatedPinesRoute: typeof AuthenticatedPinesRoute
  AuthenticatedPlanesRoute: typeof AuthenticatedPlanesRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedImpresionesRoute: AuthenticatedImpresionesRoute,
  AuthenticatedPinesRoute: AuthenticatedPinesRoute,
  AuthenticatedPlanesRoute: AuthenticatedPlanesRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
